[package]
name = "fights"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"

[dev-dependencies]
text_io = "0.1.12"
rand = "0.8.5"
rayon = "1.5.3"
